#!/usr/bin/env bash

if [ -e $HOME/.gmac_setup_done ]; then
	echo "gMac setup is done - proceeding"
else
	echo "first do gMac setup"
	exit 0
fi

echo "AppleScript Run"
install/scripts/lock.scpt
install/scripts/modifier.scpt

# bootstrap submodules (one time) - then git commit them so next time they are
# not needed
source bootstrap_submodules

# now main install
source install.sh

# later - isolated and incremental changes
pushd install
source link.sh
source brew.sh
popd
